baseurl = "/"
relativeurls = false
languageCode = "en-us"
title = "A Blog"
theme = "kube"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "Code"
    url = "/r/"
[[menu.main]]
    name = "Talks"
    url = "/talks/"
[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.social]]
    name = "fa-github fa-lg"
    url = "https://github.com/nealrichardson"
[[menu.social]]
    name = "fa-linkedin fa-lg"
    url = "https://www.linkedin.com/in/enpiar/"

[params]
    description = "A website built with Hugo."

    # # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "11.11.1"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs/"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "color-brewer"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
