baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "A Blog"
theme = "kube"
googleAnalytics = "UA-104182925-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "Code"
    url = "/r/"
[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.social]]
    name = "fa-github fa-lg"
    url = "https://github.com/nealrichardson"
[[menu.social]]
    name = "fa-twitter fa-lg"
    url = "https://twitter.com/enpiar"

[params]
    description = "A website built through Hugo and blogdown."

    twitter = "enpiar"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "color-brewer"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
